### ISSUE TITLE
calling value on an un-executed Promise produces confusing exception suggesting Deadlock

### ISSUE THREAD

**Issue by jrochkind** [ruby-concurrency/concurrent-ruby#504] opened 2016-02-06 13:51 UTC
p1 = Concurrent::Promise.new{ "Hello World!" }
    p1.value
    # raises fatal: No live threads left. Deadlock?
    p1.execute.value
    # => "Hello World!"

Would a more straightforward exception message indicating "the promise hasn't been executed yet you can't look at it's value" be possible and desirable?  

The problem/bug with the code that results in an exception is _not_ really that no live threads are left or that there may have been a deadlock (yes?), it's that you can't call #value on a Promise that has not yet been executed. 

Of course, in most cases (?) the developer should be using `Promise.execute` not `Promise.new`, unless they know what they are doing and really want `new`. But it's an easy mistake to make, since `new` seems natural; the exception should ideally make it easier to let you know what mistake you've made. 

(If it weren't too late for non-backwards-compat changes I might suggest `.new` should actually return an executed promise, (synonym for `Promise.execute`) since that's the more usual desired case, and there should be a separate `Promise.unexecuted` or `Promise.pre_executed` for the special case where you really want an unexecuted one. But I won't.)

**Comment by ianks** [comment] 2016-02-06 17:09
I would agree that Promise.new should just directly execute the promise. At least that's how it works is JS, and tends to be the most common pattern. In fact, I don't think JS even provides an API for creating and not executing it.

I do however understand that Ruby is a different language, and typically .new should not have side effects outside of the object being instantiated. Having the promise directly execute from .new could cause an API endpoint to be hit, or some other unexpected side effect, which would be confusing the user.

With all of that in mind, I think it actually makes sense to not even have .new as part of the Promise API at all! It's definitely unconventional, but in the case I believe it makes sense.

**Comment by jrochkind** [comment] 2016-02-06 19:39
Understood, mainly I'm just suggesting that for now the relatively backwards compatible step of ensuring a different more meaningful exception is raised when that happens.

**Comment by jdantonio** [comment] 2016-02-07 20:02
I like this idea and I'm going to explore it. Thank you @jrochkind for the suggestion.

The reason for the `#execute` method is a little more complicated than what's described above, but the result is the same. Basically, reordering rules make it unsafe for threads to be created (or jobs post to) from within a constructor. Ruby isn't the only language that has the problem. Java and C# have this problem, too. JavaScript doesn't because JS only has one thread and the language makes strong guarantees about ordering.

If I make this change for `Promise` then I need to make it for everything else that has an `#execute` or similar method.

The other thing I have to think about is backward compatibility. Now that c-r is being used by major projects like Rails I need to be very careful regarding semantic versioning. The sample code won't *always* raise an exception. It will only raise an exception when the only thread is the main thread. If other threads are running then the value call blocks indefinitely. Try this:

```
f1 = Concurrent::Future.execute { sleep(30) }
p1 = Concurrent::Promise.new{ "Hello World!" }
p1.value
```

This code will block until the sleep ends and the thread pool reclaims the idle thread.

I'm pretty comfortable calling this a "bug" and pushing it as a patch release, but I want to think about it a little and make sure that's appropriate. A lot will depend on how much I have to change in order to make this behavior consistent.

**Comment by jrochkind** [comment] 2016-02-07 20:22
@jdantonio Thanks! The suggestion to actually change the `new` API was just an add-on. As I explore Promises more and see how they work, I'm actually less sure it's a good idea. 

I think as a first step my primary complaint/suggest is better. If you _do_ call #value on an un-executed Promise, is there a way to get a better more description exception?

If so, I think that would be a lot easier, and less disruptive and less dangerous change, with still a very signfiicant improvement.  Is this possible, just to get a better "This promise hasnt' been executed yet" excpetion, instead of the misleading and confusing `No live threads left. Deadlock?`?

**Comment by jdantonio** [comment] 2016-02-07 20:30
@jrochkind You're first suggestion is what I'm considering--raising a descriptive exception. But I want to change all classes with an `#execute` method to behave consistently if it makes sense. At a minimum that's Promise and Future, but I want to look at ScheduledTask, TimerTask, and others. Also, none of those classes are *guaranteed* to raise an exception if `#value` is called before `#execute`. That only happens when the application has only one thread. So an argument could be made that explicitly raising an exception becomes an API/behavior change. I'm more inclined to consider the current behavior a bug, but I need to fully think through the ramifications. Another option would be to suppress the deadlock exception and make the Promise/Future/etc. block indefinitely (which is what will happen in an application with multiple threads).

**Comment by jrochkind** [comment] 2016-02-07 20:34
Ah, okay, thanks. 

Yeah, I'd consider the case where the value blocks indefinitely to _also_ be a bug. I don't think you'd ever want that to happen?

I don't think suppressing the exception and making it block indefinitely is an improvement -- I think that's still undesriable behavior, that is too easy to accidentally trigger by mistakenly using `new` instead of `execute`.  Is there any case where the caller would want that to happen intentionally? I think not? 

It seems like it's always wrong to call `value` on a promise that hasn't yet been executed (is `unscheduled`) -- true? So I'd say it would just be a bugfix to make that always reliably raise, and with a clearer exception class/description when it does.

**Comment by jdantonio** [comment] 2016-10-12 18:00
Closing. Existing promises will be deprecated soon, replaced by the new Edge ones.

**Comment by pitr-ch** [comment] 2016-10-12 19:02
P.S. In the new implementation, everything starts to execute immediately. Delayed execution can be created by `delay` factory method, or inserted anywhere in the promise chain `a_future.delay.then { ... }`

**Comment by jrochkind** [comment] 2016-10-13 03:52
Huh, so my choice is using may-change-at-any-time-in-not-backwards-compat-ways edge, or soon-to-be-deprecated mainline?  I guess if mainline is about to be deprecated, I should really be using edge already?

**Comment by jdantonio** [comment] 2016-10-13 13:34
@jrochkind Well, when you put it that way... :-)

The plan for 2.0 is to follow the example set by Ember 2.0. New features and deprecated features will coexist in the library for a time under 1.x, and the 2.0 release will simply be a removal of all deprecated features. I believe that is still what @pitr-ch is planning, and he is preparing the first merge right now. Once the new promises are part of 1.x the API will be stable and will follow the normal semver rules. @pitr-ch will have to tell you the schedule, but I don't believe the wait will be very long.

**Comment by pitr-ch** [comment] 2016-10-13 15:20
As @jdantonio said. There is one more step missing in there though, the PR will first merge the naming updates of futures to edge, then the edge is released, then they'll go to core in 1.1, then old futures are deprecated probably 1.2, then 2.0 is released. Edge may have breaking changes more often but we still follow semantic versioning, there are no deprecations though.

**Comment by jrochkind** [comment] 2016-10-14 14:57
D you think edge is pretty stable with regards to any backwards-incompat at this point, do you think I should be using Edge now?  Took a skim at edge source, and I do like what you've done with it, the API seems to make a lot more sense. 

But I consider concurrent-ruby to be a pretty low-level library, I want to be able to write code using it, lock my Gemfile with semver requirements, and not have to worry about it breaking, and ideally only very rarely have to update to a new major version. I use it in apps all over the place, and don't need it giving me any more dependency upgrade treadmill to run on. 

How much forwards compat risk do you think I'd be taking on by switching to using Edge features?  At least then, if I have find bugs or problems I can report them and have some attention paid to them instead of just "meh, we're replacing that all with edge 'soon' anyway." :)

**Comment by jrochkind** [comment] 2016-10-14 15:05
And PS: If you really recommend that everyone at least strongly consider using certain edge implementations, such as Futures, I'd suggest modifying the README to provide some hints/instructions. Of course what those hints/constructions should be is the hard part, that's up to you. :)

But I had pretty much ignored Edge because, with one of the main factors in my adoption of ruby-concurrent being it's stability with little need for me to be constantly updating my code for new versions, in dozens of app -- my reading of the README `"These features are under active development and may change frequently. They are expected not to keep backward compatibility (there may also lack tests and documentation)."` -- led me to think "Eh, that's not what I'm looking for, I'll let those who want to live on the edge deal with that, I'm sticking to the stable, tested, and fully supported."

But after filing a few issues to be told "Yeah, we're probably not going to fix that, we're focusing on edge", I'm thinking I made the wrong call maybe, and could have used more guidance in the README.  The current mainline may not in fact be stable and fully supported. :)

**Comment by jrochkind** [comment] 2016-10-14 15:09
Also, the README saying "Semantic versions will be obeyed though" about concurrent-ruby-edge -- is a pretty meaningless thing to say when concurrent-ruby-edge is at 0.x versions!  semver specifies nothing at all about 0.x version numbers. It makes me think that backwards breaking changes _could_ come with any release in concurrent-ruby-edge.

**Comment by jdantonio** [comment] 2016-10-14 15:23
@jrochkind Everything in the README about Edge is correct. Edge was created explicitly as a place to test ideas safely outside of the core gem. Specifically to reduce churn on core. That's why Edge will probably never have a 1.0 release. As you note, semver basically doesn't apply to 0.x releases.

To clarify, not everything in Edge will be going into core. Channels, for example, won't be. There were no guarantees regarding Edge. You made the right choice by using 1.x initially. The redesign of promise/future/etc. happened to work very well. It's stable, faster than 1.x, and is being used in production in several projects. So we decided to move it into Core. Once that decision was made there were several (sometimes spirited) discussions regarding specific API details and timelines. There was a possibility that things could change.

But I should also clarify that we have committed to supporting 1.x so long as it's a dependency of supported versions of Rails. That means we will continue to fix bugs in 1.x for the foreseeable future. I chose to close this issue because it was considered an enhancement and not a bug. Maybe it should be classified as a bug instead? I don't know. That's up to @pitr-ch to decide.

**Comment by jrochkind** [comment] 2016-10-14 22:38
Okay, thanks. I too am eager to see edge promise/futures in core, the edge ones look very well designed. @pitr-ch says they'll be in core in 1.1, presumably with a different name as the 'legacy' futures will still be there too. Great. I eagerly await 1.1!

**Comment by pitr-ch** [comment] 2016-10-15 06:48
I think we were tying to do `0.y.z` where `y` is breaking change and `z` is non-breaking change in edge. I am not sure if it was defined somewhere. I'll update readme. (Still no guarantee for edge though, we'll try).

Yeah the readme is correct, and it was good that new promises were in edge, we could easily do the API renaming. 

I'll leave this as an improvement. I am also marking as rejected, because we did not consider following legal order of events: new promise creation, value called on the same thread (without promise being executed), second thread initiates execution. If the error message would be aded this legal order of events would fail.

**Closed by pitr-ch** 2016-10-15 06:48 UTC
Labels: enhance

**Comment by pitr-ch** [comment] 2016-10-15 06:53
@jrochkind Thanks. The namespace for the new implementation will be `Promises` and it will deprecate `Future`, `Promise`, `IVar`, `Delay`, `dataflow`.
