### ISSUE TITLE
An error occurred while installing concurrent-ruby-ext (0.9.0)

### ISSUE THREAD

**Issue by leandrogs** [ruby-concurrency/concurrent-ruby#516] opened 2016-02-26 18:30 UTC
Hey guys! I have an 'old' project using `ruby 1.9.3-p448` installed using rbenv and `concurrent-ruby-ext 0.9.0`. Today I was trying to install my gems using `bundle install` on a new computer (ubuntu 14.04) and only `concurrent-ruby-ext` gem failed to build.

In my Gemfile I have:
```
...
gem 'rails', '= 3.2.21'
gem 'concurrent-ruby-ext', '~> 0.9.0', require: 'concurrent'
...
```

The error I got is:
```
Installing concurrent-ruby-ext 0.9.0 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for libkern/OSAtomic.h... no
creating Makefile

make
compiling rb_concurrent.c
compiling atomic_reference.c
compiling atomic_fixnum.c
In file included from atomic_fixnum.c:5:0:
ruby_193_compatible.h: In function ‘rb_error_arity’:
ruby_193_compatible.h:20:3: warning: passing argument 2 of ‘rb_raise’ makes pointer from integer without a cast [enabled by default]
   rb_raise(rb_eTypeError, err_mess);
   ^
In file included from /usr/include/ruby-1.9.1/ruby.h:32:0,
                 from atomic_fixnum.c:1:
/usr/include/ruby-1.9.1/ruby/ruby.h:1172:27: note: expected ‘const char *’ but argument is of type ‘VALUE’
 PRINTF_ARGS(NORETURN(void rb_raise(VALUE, const char*, ...)), 2, 3);
                           ^
/usr/include/ruby-1.9.1/ruby/ruby.h:42:3: note: in definition of macro ‘PRINTF_ARGS’
   decl __attribute__((format(printf, string_index, first_to_check)))
   ^
/usr/include/ruby-1.9.1/ruby/ruby.h:1172:13: note: in expansion of macro ‘NORETURN’
 PRINTF_ARGS(NORETURN(void rb_raise(VALUE, const char*, ...)), 2, 3);
             ^
In file included from atomic_fixnum.c:5:0:
ruby_193_compatible.h:20:3: error: format not a string literal and no format arguments [-Werror=format-security]
   rb_raise(rb_eTypeError, err_mess);
   ^
cc1: some warnings being treated as errors
make: *** [atomic_fixnum.o] Error 1


Gem files will remain installed in /tmp/bundler20160226-18427-13v8kyrconcurrent-ruby-ext-0.9.0/gems/concurrent-ruby-ext-0.9.0 for inspection.
Results logged to /tmp/bundler20160226-18427-13v8kyrconcurrent-ruby-ext-0.9.0/gems/concurrent-ruby-ext-0.9.0/ext/concurrent/gem_make.out
```

Am I missing something? Using my work computer I can `bundle install` without any problem...

**Comment by ianks** [comment] 2016-02-26 20:26
This looks like you are installing the gem for Ruby-1.9.1. 1.9.3 is the oldest supported MRI version.

**Comment by leandrogs** [comment] 2016-02-27 01:49
@ianks I can only fix this by using newer gem version?

**Comment by jdantonio** [comment] 2016-02-27 02:54
I don't know anything about rbenv (I use rvm myself) but it looks like your environment may have some issues. The build process seems to be trying to use include files from the system's 1.9.1 install.

**Comment by jdantonio** [comment] 2016-03-02 01:26
@leandrogs Have you had made any progress on this?

**Comment by leandrogs** [comment] 2016-03-04 01:20
@jdantonio I was able to `bundle install` using `concurrent-ruby` gem instead of `concurrent-ruby-ext`

**Comment by jdantonio** [comment] 2016-03-04 14:06
:-)

**Comment by RJPercival** [comment] 2016-06-07 15:54
This issue should not be closed - @leandrogs didn't fix the problem, he just stopped trying to compile the extension. I can reproduce this issue, so long as my compiler treats "format-security" warnings as errors.

**Comment by jdantonio** [comment] 2016-06-08 08:53
@RJPercival Thank you for letting us know that this is a problem for you, too. TBH, none of us work with C very much so your help would be greatly appreciated. I wasn't aware that there was such a things as a "format-security" option. Can you please provide steps to reproduce? (I don't know how to enable that option--I simply run the rake task to build.) Also, do you know if it's possible to enable that (or similar) option on OS X with Xcode, or is this a Linux-specific issue? I generally do my development on a Mac. I can setup a Linux machine if necessary, but it will help to know how widespread the problem may be.

**Comment by RJPercival** [comment] 2016-06-08 11:03
GCC can take a "-Werror=format-security" flag that causes potentially dangerous calls to printf-style functions to be treated as compilation errors. On my Ubuntu system, this flag is enabled by default and so appears in the Makefile generated for the concurrent-ruby extension. I expect you should be able to reproduce this on OS X, but you might have to manually edit the Makefile to add that flag, since I'm not sure how you'd make it be added automatically.

I've put together PR #536 that fixes the issue, at least on my system. It just updates the implementation of the functions in ruby_193_compatible.h to more closely mirror their implementations in Ruby 2.0.

**Comment by leandrogs** [comment] 2016-06-08 11:17
Nice to know that someone is working on this issue :D

**Comment by jdantonio** [comment] 2016-06-12 20:04
I've uploaded an pre-release build v1.0.3.pre1 to the GitHub releases page (I have _not_ published the pre-release to Rubygems). Please test the extension gem by downloading it directly and installing it and let me know if it now works on the affected Linux versions.

**Comment by RJPercival** [comment] 2016-06-15 14:02
On Ubuntu 14.04 LTS:
```
Successfully installed concurrent-ruby-1.0.3.pre1
Building native extensions.  This could take a while...
Successfully installed concurrent-ruby-ext-1.0.3.pre1
2 gems installed
Installing ri documentation for concurrent-ruby-1.0.3.pre1...
Installing ri documentation for concurrent-ruby-ext-1.0.3.pre1...
Installing RDoc documentation for concurrent-ruby-1.0.3.pre1...
Installing RDoc documentation for concurrent-ruby-ext-1.0.3.pre1...
```

**Comment by jdantonio** [comment] 2016-06-20 00:34
Awesome! We'll wait to see what happens with #539 then publish a new release.

**Comment by jdantonio** [comment] 2016-06-24 14:17
We'll be publishing 1.0.3 with this fix shortly. Since we know it's fixed in the latest pre-release I'm going to close this issue.

**Closed by jdantonio** 2016-06-24 14:17 UTC
Labels: bug
