### ISSUE TITLE
Concurrent::Actor used with :tell eats all the memory

### ISSUE THREAD

**Issue by tscholz** [ruby-concurrency/concurrent-ruby#671] opened 2017-08-25 09:53 UTC
Hi there

Thank you for the great gem!

Ruby consumes a huge amount of memory when calling an actor using `:tell` many times.  I'm not sure if this is a bug or if we can't use the actor that way. Thank you for looking into this.

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'concurrent-ruby-edge', '0.3.1', require: 'concurrent-edge'
end

class Counter < Concurrent::Actor::Context
  def initialize(initial_value)
    @count = initial_value
  end

  # override on_message to define actor's behaviour
  def on_message(message)
    case message
      when Integer
        @count += message
      when :count
        @count
    else
      pass
    end
  end
end

counter = Counter.spawn(:first, 0)

5_000_000.times do
  # do some work
  counter.tell 1
end

puts counter.ask! :count

puts "Press a key to exit programm."
gets
```

******
-   Operating system: mac
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: no
-   `concurrent-ruby-edge` used: yes
-   `ruby` used: 2.3.1, 2.4

**Comment by torce** [comment] 2017-10-05 19:26
Hi, 
I was playing with your example a bit. Seems that the loop is sending more messages than the actor can process. Since the actor is being executed a the default thread pool with a unlimited job queue, the messages are being accumulated in the queue, causing that memory issue.

One way to solve this is using a custom executor with a bounded job queue, so spawning your actor with:
```ruby
counter = Counter.spawn(name: :first,
                        args: [0],
                        executor: Concurrent::FixedThreadPool.new(1, max_queue: 5000))
```
should solve the problem. In my machine, with this change, all the messages are processed and the memory usage is constant (about 22Mb).

Additionally, you can override the `default_executor` method in the actor to use a custom executor.
Regards.

**Comment by torce** [comment] 2017-10-05 19:42
Hi,
I was playing with your example a bit. Seems that everytime you send a message to the actor, it's stored in an array (`@stash`) in `Concurrent::SerializedExecution`. Since the loop sends more messages than the counter actor can process, a lot of unprocessed messages are stored in that array.

I couldn't find a way to configure a maximum size for that message array. Using a custom executor with a bounded job queue doesn't solve the problem.
Regards.

**Comment by pitr-ch** [comment] 2017-11-18 11:37
Hi, sorry, unfortunately there is no bounded mailbox implementation yet. I am aware of the issue and we'll resolve it eventually.

**Comment by pitr-ch** [comment] 2017-11-18 11:40
I the problem is already tracked in another issue, I am closing this one.

**Closed by pitr-ch** 2017-11-18 11:40 UTC
Labels: question
